# .github/workflows/ci.yml
name: CI Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    name: CI Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sleep/Delay timer
        run: sleep 60
      - name: CI smoke test
        run: echo "✅ CI is running"
